FROM osrf/ros:melodic-desktop-full

RUN apt-get update && apt-get install -y vim \
        'ros-melodic-heron-*' \
        ros-melodic-imu-tools \
        ros-melodic-uuv-simulator \
        less \
        && rm -rf /var/lib/apt/lists/*

RUN echo 'source /opt/ros/melodic/setup.bash' >> ~/.bashrc

CMD ["roslaunch", "heron_gazebo", "heron_world.launch"]

